Formatting fix

diff --git a/bin/rosman b/bin/rosman
--- a/bin/rosman
+++ b/bin/rosman
@@ -4,15 +4,15 @@
 
 . /opt/ros/kinetic/setup.bash
 
-find_string() {    
-    grep $1 $2 >/dev/null
-    if [ $? -eq 0 ]; then
-	echo "Found!"
-	return $(( 1 ));
-    else
-	echo "Not found!"
-	return $(( 0 ));
-    fi
+find_string() {
+  grep $1 $2 >/dev/null
+  if [ $? -eq 0 ]; then
+	  echo "Found!"
+	  return $(( 1 ));
+  else
+	  echo "Not found!"
+	  return $(( 0 ));
+  fi
 }
 
 ################################################################################
@@ -20,27 +20,27 @@ find_string() {
 CATKIN_WS=$HOME/catkin_ws
 
 if [ ! -d $CATKIN_WS ]; then
-    mkdir -p $CATKIN_WS/src
-    cd $CATKIN_WS/src
-    catkin_init_workspace
-    if [ -f $HOME/.bashrc ]; then
-	. "$CATKIN_WS"/devel/setup.bash
-	echo ". "$CATKIN_WS"/devel/setup.bash" >> $HOME/.bashrc 
-    fi
-    if [ -f $HOME/.zshrc ]; then
-	. "$CATKIN_WS"/devel/setup.zsh
-	echo ". "$CATKIN_WS"/devel/setup.zsh" >> $HOME/.zshrc 
-    fi
-# else
+  mkdir -p $CATKIN_WS/src
+  cd $CATKIN_WS/src
+  catkin_init_workspace
+  if [ -f $HOME/.bashrc ]; then
+	  . "$CATKIN_WS"/devel/setup.bash
+	  echo ". "$CATKIN_WS"/devel/setup.bash" >> $HOME/.bashrc
+  fi
+  if [ -f $HOME/.zshrc ]; then
+	  . "$CATKIN_WS"/devel/setup.zsh
+	  echo ". "$CATKIN_WS"/devel/setup.zsh" >> $HOME/.zshrc
+  fi
+  # else
 fi
 
 cd $CATKIN_WS/src
 if [ ! -d $CATKIN_WS/build ]; then
-    catkin_init_workspace
+  catkin_init_workspace
 fi
 
 if [ ! -d $CATKIN_WS/devel ]; then
-    catkin_init_workspace
+  catkin_init_workspace
 fi
 
 ################################################################################
@@ -48,40 +48,40 @@ fi
 cd $CATKIN_WS/src
 catkin_create_pkg $1 std_msgs roscpp
 
-echo "#include<ros/ros.h>  
-#include<pcl/point_cloud.h>  
-#include<pcl_conversions/pcl_conversions.h>  
-#include<sensor_msgs/PointCloud2.h>  
-      
-int main (int argc, char **argv)  
-{  
-  ros::init (argc, argv, \"pcl_create\");  
-  ros::NodeHandle nh;  
-  ros::Publisher pcl_pub = nh.advertise<sensor_msgs::PointCloud2> (\"pcl_output\", 1);  
-  pcl::PointCloud<pcl::PointXYZ> cloud;  
-  sensor_msgs::PointCloud2 output;  
-  // Fill in the cloud data  
-  cloud.width = 100;  
-  cloud.height = 1;  
-  cloud.points.resize(cloud.width * cloud.height);  
-  for (size_t i = 0; i < cloud.points.size(); ++i)  
-    {  
-      cloud.points[i].x = 1024 * rand () / (RAND_MAX + 1.0f);  
-      cloud.points[i].y = 1024 * rand () / (RAND_MAX + 1.0f);  
-      cloud.points[i].z = 1024 * rand () / (RAND_MAX + 1.0f);  
-    }  
-      
-  //Convert the cloud to ROS message  
-  pcl::toROSMsg(cloud, output);  
-  output.header.frame_id = \"odom\";//this has been done in order to be able to visualize our PointCloud2 message on the RViz visualizer  
-  ros::Rate loop_rate(1);  
-  while (ros::ok())  
-    {  
-      pcl_pub.publish(output);  
-      ros::spinOnce();  
-      loop_rate.sleep();  
-    }  
-  return 0;  
+echo "#include<ros/ros.h>
+#include<pcl/point_cloud.h>
+#include<pcl_conversions/pcl_conversions.h>
+#include<sensor_msgs/PointCloud2.h>
+
+int main (int argc, char **argv)
+{
+  ros::init (argc, argv, \"pcl_create\");
+  ros::NodeHandle nh;
+  ros::Publisher pcl_pub = nh.advertise<sensor_msgs::PointCloud2> (\"pcl_output\", 1);
+  pcl::PointCloud<pcl::PointXYZ> cloud;
+  sensor_msgs::PointCloud2 output;
+  // Fill in the cloud data
+  cloud.width = 100;
+  cloud.height = 1;
+  cloud.points.resize(cloud.width * cloud.height);
+  for (size_t i = 0; i < cloud.points.size(); ++i)
+    {
+      cloud.points[i].x = 1024 * rand () / (RAND_MAX + 1.0f);
+      cloud.points[i].y = 1024 * rand () / (RAND_MAX + 1.0f);
+      cloud.points[i].z = 1024 * rand () / (RAND_MAX + 1.0f);
+    }
+
+  //Convert the cloud to ROS message
+  pcl::toROSMsg(cloud, output);
+  output.header.frame_id = \"odom\";//this has been done in order to be able to visualize our PointCloud2 message on the RViz visualizer
+  ros::Rate loop_rate(1);
+  while (ros::ok())
+    {
+      pcl_pub.publish(output);
+      ros::spinOnce();
+      loop_rate.sleep();
+    }
+  return 0;
 }
 " >> $1/src/$1.cpp
 
diff --git a/plugins/python b/plugins/python
--- a/plugins/python
+++ b/plugins/python
@@ -1,224 +1,224 @@
 #!/usr/bin/env sh
 
 python_install_pyenv() {
-    tip "install pyenv"
-    github_upgrade pyenv/pyenv $HOME/.pyenv
+  tip "install pyenv"
+  github_upgrade pyenv/pyenv $HOME/.pyenv
 
-    tip "pyenv_setenv"
-    pyenv_setenv
+  tip "pyenv_setenv"
+  pyenv_setenv
 
-    tip "install python"
-    pyenv install $PYTHON3_VERSION
-    pyenv global $PYTHON3_VERSION
+  tip "install python"
+  pyenv install $PYTHON3_VERSION
+  pyenv global $PYTHON3_VERSION
 
-    tip "pyenv whence rackup"
-    pyenv whence rackup
+  tip "pyenv whence rackup"
+  pyenv whence rackup
 
-    # use $HOME/.local pip
-    ome_dev_path $HOME/.local
+  # use $HOME/.local pip
+  ome_dev_path $HOME/.local
 }
 
 python_install_bin() {
-    #deps
-    get_os_type
-    case $OME_OS in
-        # Linux
-        # $OS_DEBIAN) ;;
-        # $OS_UBUNTU) ;;
-        $OS_DEBIAN|$OS_UBUNTU)
-            sudo apt install python3 python3-distutils python3-dev # python3-pip
-            ;;
-        # $OS_REDHAT) ;;
-        # $OS_FEDORA) ;;
-        $OS_REDHAT|$OS_FEDORA)
-            sudo yum install -y python3 python3-devel;;
-        $OS_ARCH)
-            sudo pacman -S python3
-            ;;
-        $OS_GENTOO)
-            emerge python3
-            ;;
-        $OS_SUSE) ;;
-        $OS_SLACKWARE) ;;
-        $OS_NIXOS) ;;
-        $OS_VOID) ;;
-        $OS_ALPINE) ;;
-        $OS_MAGEIA) ;;
-        $OS_SLITAZ) ;;
-        $OS_GUIXSD) ;;
-        # Unix
-        $OS_MACOS)
-            brew install python3
-            ;;
-        $OS_AIX) ;;
-        $OS_SOLARIS) ;;
-        $OS_FREEBSD)
-            sudo pkg install python38
-            ;;
-        $OS_OPENBSD)
-            sudo pkg install python38
-            ;;
-        $OS_NETBSD) ;;
-        $OS_DFBSD) ;;
-        # Windows
-        $OS_CYGWIN)
-            apt install python3
-            ;;
-        $OS_MSYS2)
-            pacman -S mingw-w64-x86_64-python mingw-w64-x86_64-python-pip
-            ;;
-        # Other
-        $OS_UNKNOW) ;;
-    esac
+  #deps
+  get_os_type
+  case $OME_OS in
+    # Linux
+    # $OS_DEBIAN) ;;
+    # $OS_UBUNTU) ;;
+    $OS_DEBIAN|$OS_UBUNTU)
+      sudo apt install python3 python3-distutils python3-dev # python3-pip
+      ;;
+    # $OS_REDHAT) ;;
+    # $OS_FEDORA) ;;
+    $OS_REDHAT|$OS_FEDORA)
+      sudo yum install -y python3 python3-devel;;
+    $OS_ARCH)
+      sudo pacman -S python3
+      ;;
+    $OS_GENTOO)
+      emerge python3
+      ;;
+    $OS_SUSE) ;;
+    $OS_SLACKWARE) ;;
+    $OS_NIXOS) ;;
+    $OS_VOID) ;;
+    $OS_ALPINE) ;;
+    $OS_MAGEIA) ;;
+    $OS_SLITAZ) ;;
+    $OS_GUIXSD) ;;
+    # Unix
+    $OS_MACOS)
+      brew install python3
+      ;;
+    $OS_AIX) ;;
+    $OS_SOLARIS) ;;
+    $OS_FREEBSD)
+      sudo pkg install python38
+      ;;
+    $OS_OPENBSD)
+      sudo pkg install python38
+      ;;
+    $OS_NETBSD) ;;
+    $OS_DFBSD) ;;
+    # Windows
+    $OS_CYGWIN)
+      apt install python3
+      ;;
+    $OS_MSYS2)
+      pacman -S mingw-w64-x86_64-python mingw-w64-x86_64-python-pip
+      ;;
+    # Other
+    $OS_UNKNOW) ;;
+  esac
 }
 
 python_install() {
-    local oldir=`pwd`
+  local oldir=`pwd`
 
-    python_install_bin
-    # python_install_pyenv
+  python_install_bin
+  # python_install_pyenv
 
-    tip "set pip mirror"
-    if [ ! -f $HOME/.pip/pip.conf ]; then
-        mkdir -p $HOME/.pip/
-        echo "[global]" >> $HOME/.pip/pip.conf
-        echo "index-url = http://mirrors.aliyun.com/pypi/simple/" >> $HOME/.pip/pip.conf
-        echo "" >> $HOME/.pip/pip.conf
-        echo "[install]" >> $HOME/.pip/pip.conf
-        echo "trusted-host=mirrors.aliyun.com" >> $HOME/.pip/pip.conf
-        # echo "install-option=--prefix=~/.local" >> $HOME/.pip/pip.conf
+  tip "set pip mirror"
+  if [ ! -f $HOME/.pip/pip.conf ]; then
+    mkdir -p $HOME/.pip/
+    echo "[global]" >> $HOME/.pip/pip.conf
+    echo "index-url = http://mirrors.aliyun.com/pypi/simple/" >> $HOME/.pip/pip.conf
+    echo "" >> $HOME/.pip/pip.conf
+    echo "[install]" >> $HOME/.pip/pip.conf
+    echo "trusted-host=mirrors.aliyun.com" >> $HOME/.pip/pip.conf
+    # echo "install-option=--prefix=~/.local" >> $HOME/.pip/pip.conf
+  fi
+
+  if [ "$OME_OS" = "$OS_MSYS2" ] && [ ! -f "$USERPROFILE/pip/pip.ini" ]; then
+    # export PATH="$USERPROFILE/.local/bin:$PATH"
+    mkdir -p $USERPROFILE/pip/
+    echo "[global]" >> $USERPROFILE/pip/pip.ini
+    echo "index-url = http://mirrors.aliyun.com/pypi/simple/" >> $USERPROFILE/pip/pip.ini
+    echo "" >> $USERPROFILE/pip/pip.ini
+    echo "[install]" >> $USERPROFILE/pip/pip.ini
+    echo "trusted-host=mirrors.aliyun.com" >> $USERPROFILE/pip/pip.ini
+    # echo "install-option=--prefix=`cygpath -m ~/.local`" >> $USERPROFILE/pip/pip.ini
+  fi
+
+  # if ! command -v pip3 >/dev/null 2>&1; then
+  if [ "`command -v pip3`" = "" ]; then
+    tip "install pip3"
+    cd $HOME/Downloads/
+    if [ ! -f get-pip.py ]; then
+      curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
     fi
+    # python3 get-pip.py --user
+    # curl https://bootstrap.pypa.io/get-pip.py | python3
+    #11 python3 get-pip.py --prefix=$OME_PREFIX
+  else
+    # pip3 install --prefix $OME_PREFIX --user -U pip
+    #11 pip3 install --prefix $OME_PREFIX --upgrade pip -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
+    echo ""
+  fi
 
-    if [ "$OME_OS" = "$OS_MSYS2" ] && [ ! -f "$USERPROFILE/pip/pip.ini" ]; then
-        # export PATH="$USERPROFILE/.local/bin:$PATH"
-        mkdir -p $USERPROFILE/pip/
-        echo "[global]" >> $USERPROFILE/pip/pip.ini
-        echo "index-url = http://mirrors.aliyun.com/pypi/simple/" >> $USERPROFILE/pip/pip.ini
-        echo "" >> $USERPROFILE/pip/pip.ini
-        echo "[install]" >> $USERPROFILE/pip/pip.ini
-        echo "trusted-host=mirrors.aliyun.com" >> $USERPROFILE/pip/pip.ini
-        # echo "install-option=--prefix=`cygpath -m ~/.local`" >> $USERPROFILE/pip/pip.ini
-    fi
+  tip "check pip3"
+  which pip3
+  pip3 --version
 
-    # if ! command -v pip3 >/dev/null 2>&1; then
-    if [ "`command -v pip3`" = "" ]; then
-        tip "install pip3"
-        cd $HOME/Downloads/
-        if [ ! -f get-pip.py ]; then
-            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
-        fi
-        # python3 get-pip.py --user
-        # curl https://bootstrap.pypa.io/get-pip.py | python3
-        #11 python3 get-pip.py --prefix=$OME_PREFIX
-    else
-        # pip3 install --prefix $OME_PREFIX --user -U pip
-        #11 pip3 install --prefix $OME_PREFIX --upgrade pip -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
-        echo ""
-    fi
+  # tip "pip3 version"
+  # pip3 --version
 
-    tip "check pip3"
-    which pip3
-    pip3 --version
+  tip "install setuptools"
+  # pip3 install --prefix=$OME_PREFIX -U sqlalchemy -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
+  pip3 install --prefix $OME_PREFIX -U setuptools
 
-    # tip "pip3 version"
-    # pip3 --version
+  tip "install virtualenv"
+  pip3 install --prefix $OME_PREFIX -U virtualenv
 
-    tip "install setuptools"
-    # pip3 install --prefix=$OME_PREFIX -U sqlalchemy -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
-    pip3 install --prefix $OME_PREFIX -U setuptools
+  tip "install pipenv"
+  pip3 install --prefix $OME_PREFIX -U pipenv
 
-    tip "install virtualenv"
-    pip3 install --prefix $OME_PREFIX -U virtualenv
+  tip "install poetry"
+  pip3 install --prefix $OME_PREFIX poetry
 
-    tip "install pipenv"
-    pip3 install --prefix $OME_PREFIX -U pipenv
+  tip "install hatch"
+  pip3 install --prefix $OME_PREFIX hatch
 
-    tip "install poetry"
-    pip3 install --prefix $OME_PREFIX poetry
+  tip "install python language server"
+  # pip3 install --prefix $OME_PREFIX -U python-language-server
+  pip3 install --prefix $OME_PREFIX -U 'python-language-server[all]'
 
-    tip "install hatch"
-    pip3 install --prefix $OME_PREFIX hatch
+  tip "install build tools:gyp"
+  github_upgrade chromium/gyp $OME_REPO/gyp
+  cd $OME_REPO/gyp/
+  pip3 install --prefix $OME_PREFIX -U .
 
-    tip "install python language server"
-    # pip3 install --prefix $OME_PREFIX -U python-language-server
-    pip3 install --prefix $OME_PREFIX -U 'python-language-server[all]'
+  tip "install build tools:waf"
+  git_upgrade "https://gitlab.com" ita1024/waf $OME_REPO/waf
+  cd $OME_REPO/waf/
+  python3 ./waf-light configure build
+  cp -rf ./waf $OME_PREFIX/bin/
 
-    tip "install build tools:gyp"
-    github_upgrade chromium/gyp $OME_REPO/gyp
-    cd $OME_REPO/gyp/
-    pip3 install --prefix $OME_PREFIX -U .
+  # tip "install build tools:scons"
+  # git_upgrade "https://github.com" SCons/scons $OME_REPO/scons
+  # cd $OME_REPO/scons/
+  # python3 bootstrap.py build/scons
+  # if [ -d $OME_REPO/scons/build/scons/ ]; then
+  # cd $OME_REPO/scons/build/scons/
+  # pip3 install --prefix $OME_PREFIX -U .
+  # else
+  # echo_error "gen scons failed!"
+  # fi
 
-    tip "install build tools:waf"
-    git_upgrade "https://gitlab.com" ita1024/waf $OME_REPO/waf
-    cd $OME_REPO/waf/
-    python3 ./waf-light configure build
-    cp -rf ./waf $OME_PREFIX/bin/
+  tip "install OutputCheck tool"
+  pip3 install --prefix $OME_PREFIX -U OutputCheck
 
-    # tip "install build tools:scons"
-    # git_upgrade "https://github.com" SCons/scons $OME_REPO/scons
-    # cd $OME_REPO/scons/
-    # python3 bootstrap.py build/scons
-    # if [ -d $OME_REPO/scons/build/scons/ ]; then
-        # cd $OME_REPO/scons/build/scons/
-        # pip3 install --prefix $OME_PREFIX -U .
-    # else
-        # echo_error "gen scons failed!"
-    # fi
+  # pip install ipython jupyter rope jedi flake8 importmagic autopep8 yapf
+  tip "install ebook build tool"
+  pip3 install --prefix $OME_PREFIX -U jinja2
+  pip3 install --prefix $OME_PREFIX -U markupsafe
+  pip3 install --prefix $OME_PREFIX -U pygments
+  pip3 install --prefix $OME_PREFIX -U sphinx
+  pip3 install --prefix $OME_PREFIX -U docutils
+  # pip3 install --prefix $OME_PREFIX -U wsgiref
 
-    tip "install OutputCheck tool"
-    pip3 install --prefix $OME_PREFIX -U OutputCheck
-
-    # pip install ipython jupyter rope jedi flake8 importmagic autopep8 yapf
-    tip "install ebook build tool"
-    pip3 install --prefix $OME_PREFIX -U jinja2
-    pip3 install --prefix $OME_PREFIX -U markupsafe
-    pip3 install --prefix $OME_PREFIX -U pygments
-    pip3 install --prefix $OME_PREFIX -U sphinx
-    pip3 install --prefix $OME_PREFIX -U docutils
-    # pip3 install --prefix $OME_PREFIX -U wsgiref
-
-    tip "install McCabe complexity checker"
-    pip3 install --prefix $OME_PREFIX -U mccabe
-    cd $oldir
+  tip "install McCabe complexity checker"
+  pip3 install --prefix $OME_PREFIX -U mccabe
+  cd $oldir
 }
 
 python_uninstall() {
-    sudo python3 -m pip uninstall -y pip setuptools
+  sudo python3 -m pip uninstall -y pip setuptools
 }
 
 python_exist_p() {
-    echo_error "'python_exist_p' not implemented"
+  echo_error "'python_exist_p' not implemented"
 }
 
 python_info() {
-    if [ "`command -v python2`" != "" ]; then
-        PY2VER="`python2 --version 2>&1 | cut -c 8-`"
-    else
-        PY2VER="!miss!"
-    fi
+  if [ "`command -v python2`" != "" ]; then
+    PY2VER="`python2 --version 2>&1 | cut -c 8-`"
+  else
+    PY2VER="!miss!"
+  fi
 
-    if [ "`command -v python3`" != "" ]; then
-        PY3VER="`python3 --version | cut -c 8-`"
-    else
-        PY3VER="!miss!"
-    fi
-    if [ "`command -v python2`" != "" ] || [ "`command -v python3`" != "" ]; then
-        ome_show "Python" "py2:$PY2VER | py3:$PY3VER"
-    fi
+  if [ "`command -v python3`" != "" ]; then
+    PY3VER="`python3 --version | cut -c 8-`"
+  else
+    PY3VER="!miss!"
+  fi
+  if [ "`command -v python2`" != "" ] || [ "`command -v python3`" != "" ]; then
+    ome_show "Python" "py2:$PY2VER | py3:$PY3VER"
+  fi
 }
 
 # PYTHON2_VERSION=2.7.17
 # PYTHON3_VERSION=3.8.1
 pyenv_setenv() {
-    export PYENV_ROOT="$HOME/.pyenv"
-    export PATH="$PYENV_ROOT/bin:$PATH"
+  export PYENV_ROOT="$HOME/.pyenv"
+  export PATH="$PYENV_ROOT/bin:$PATH"
 
-    # if [ "$OME_OS" = "$OS_MSYS2" ]; then
-        # export PATH="$USERPROFILE/.local/bin:$PATH"
-    # fi
-    if command -v pyenv 1>/dev/null 2>&1; then
-        eval "$(pyenv init -)"
-    fi
-    # export PYTHON_BUILD_MIRROR_URL="http://mirrors.sohu.com/python/2.7.12/"
+  # if [ "$OME_OS" = "$OS_MSYS2" ]; then
+  # export PATH="$USERPROFILE/.local/bin:$PATH"
+  # fi
+  if command -v pyenv 1>/dev/null 2>&1; then
+    eval "$(pyenv init -)"
+  fi
+  # export PYTHON_BUILD_MIRROR_URL="http://mirrors.sohu.com/python/2.7.12/"
 }
 # pyenv_setenv
